import 'package:cloud_firestore/cloud_firestore.dart';

/// A data model for a court in South Africa.
class CourtModel {
  String? courtId;
  final String courtName;
  final String courtLevel;
  final String courtAddress;
  final String city;
  final String province;
  final String officeId;
  final GeoPoint location;

  CourtModel({
    this.courtId,
    required this.courtName,
    required this.courtLevel,
    required this.courtAddress,
    required this.city,
    required this.province,
    required this.officeId,
    required this.location,
  });

  factory CourtModel.fromJson(Map<String, dynamic> json) {
    return CourtModel(
      courtName: json['courtName'],
      courtLevel: json['courtLevel'],
      courtAddress: json['courtAddress'],
      city: json['city'],
      province: json['province'],
      officeId: json['fastCorrOffice'],
      location: json['location'],
    );
  }

  factory CourtModel.fromSnapshot(DocumentSnapshot snap) {
    return CourtModel(
      courtId: snap.id,
      courtName: snap['courtName'],
      courtLevel: snap['courtLevel'],
      courtAddress: snap['courtAddress'],
      city: snap['city'],
      province: snap['province'],
      officeId: snap['fastCorrOffice'],
      location: snap['location'],
    );
  }

  Map<String, dynamic> toJson() {
    return {
      'courtId': courtId,
      'courtName': courtName,
      'courtLevel': courtLevel,
      'courtAddress': courtAddress,
      'city': city,
      'province': province,
      'fastCorrOffice': officeId,
      'location': location,
    };
  }

  CourtModel copyWith({
    String? courtId,
    String? courtName,
    String? courtLevel,
    String? courtAddress,
    String? city,
    String? province,
    String? fastCorrOffice,
    GeoPoint? location,
  }) {
    return CourtModel(
      courtId: courtId ?? this.courtId,
      courtName: courtName ?? this.courtName,
      courtLevel: courtLevel ?? this.courtLevel,
      courtAddress: courtAddress ?? this.courtAddress,
      city: city ?? this.city,
      province: province ?? this.province,
      officeId: fastCorrOffice ?? this.officeId,
      location: location ?? this.location,
    );
  }
}

final List<CourtModel> courtList = [
  // --- High Courts ---
  CourtModel(
    courtName: 'Eastern Cape Division, Makhanda',
    courtLevel: 'High Court (Main Seat)',
    courtAddress: '104 - 106 High Street, Makhanda, 6139',
    city: 'Makhanda',
    province: 'Eastern Cape',
    officeId: '',
    location: const GeoPoint(-33.3113, 26.5255),
  ),
  CourtModel(
    courtName: 'Eastern Cape Local Division, Bhisho',
    courtLevel: 'High Court (Local Seat)',
    courtAddress: '10 Independence Avenue, Bhisho, 5605',
    city: 'Bhisho',
    province: 'Eastern Cape',
    officeId: '',
    location: const GeoPoint(-32.8465, 27.4373),
  ),
  CourtModel(
    courtName: 'Eastern Cape Local Division, Mthatha',
    courtLevel: 'High Court (Local Seat)',
    courtAddress: 'Cnr Victoria & Frere Roads, Mthatha, 5099',
    city: 'Mthatha',
    province: 'Eastern Cape',
    officeId: '',
    location: const GeoPoint(-31.5932, 28.7845),
  ),
  CourtModel(
    courtName: 'Eastern Cape Local Division, Gqeberha',
    courtLevel: 'High Court (Local Seat)',
    courtAddress: '2 Bird Street, Central, Gqeberha, 6001',
    city: 'Gqeberha',
    province: 'Eastern Cape',
    officeId: '',
    location: const GeoPoint(-33.9634, 25.6174),
  ),
  CourtModel(
    courtName: 'Free State Division, Bloemfontein',
    courtLevel: 'High Court (Main Seat)',
    courtAddress: 'Cnr President Brand & Fountain Streets, Bloemfontein, 9301',
    city: 'Bloemfontein',
    province: 'Free State',
    officeId: '',
    location: const GeoPoint(-29.1162, 26.2202),
  ),
  CourtModel(
    courtName: 'Gauteng Division, Pretoria',
    courtLevel: 'High Court (Main Seat)',
    courtAddress: 'Cnr Paul Kruger & Madiba Streets, Pretoria, 0002',
    city: 'Pretoria',
    province: 'Gauteng',
    officeId: '',
    location: const GeoPoint(-25.7461, 28.1883),
  ),
  CourtModel(
    courtName: 'Gauteng Local Division, Johannesburg',
    courtLevel: 'High Court (Local Seat)',
    courtAddress: 'Cnr Kruis & Pritchard Streets, Johannesburg, 2001',
    city: 'Johannesburg',
    province: 'Gauteng',
    officeId: '',
    location: const GeoPoint(-26.2023, 28.0436),
  ),
  CourtModel(
    courtName: 'KwaZulu-Natal Division, Pietermaritzburg',
    courtLevel: 'High Court (Main Seat)',
    courtAddress: '301 Church Street, Pietermaritzburg, 3201',
    city: 'Pietermaritzburg',
    province: 'KwaZulu-Natal',
    officeId: '',
    location: const GeoPoint(-29.6015, 30.3794),
  ),
  CourtModel(
    courtName: 'KwaZulu-Natal Local Division, Durban',
    courtLevel: 'High Court (Local Seat)',
    courtAddress: '12 Dullah Omar Grove, Durban, 4001',
    city: 'Durban',
    province: 'KwaZulu-Natal',
    officeId: '',
    location: const GeoPoint(-29.8559, 31.0267),
  ),
  CourtModel(
    courtName: 'Limpopo Division, Polokwane',
    courtLevel: 'High Court (Main Seat)',
    courtAddress: '34 Landdros Maré Street, Polokwane, 0700',
    city: 'Polokwane',
    province: 'Limpopo',
    officeId: '',
    location: const GeoPoint(-23.9069, 29.4582),
  ),
  CourtModel(
    courtName: 'Limpopo Local Division, Thohoyandou',
    courtLevel: 'High Court (Local Seat)',
    courtAddress: 'Government Complex, Thohoyandou, 0950',
    city: 'Thohoyandou',
    province: 'Limpopo',
    officeId: '',
    location: const GeoPoint(-22.9511, 30.4800),
  ),
  CourtModel(
    courtName: 'Mpumalanga Division, Mbombela',
    courtLevel: 'High Court (Main Seat)',
    courtAddress: 'Cnr Samora Machel Drive & Kaapschehoop Road, Mbombela, 1200',
    city: 'Mbombela',
    province: 'Mpumalanga',
    officeId: '',
    location: const GeoPoint(-25.4674, 30.9634),
  ),
  CourtModel(
    courtName: 'Mpumalanga Local Division, Middelburg',
    courtLevel: 'High Court (Local Seat)',
    courtAddress: '22 Beyers Naude Street, Middelburg, 1050',
    city: 'Middelburg',
    province: 'Mpumalanga',
    officeId: '',
    location: const GeoPoint(-25.7681, 29.4678),
  ),
  CourtModel(
    courtName: 'North West Division, Mahikeng',
    courtLevel: 'High Court (Main Seat)',
    courtAddress: 'University Drive, Mmabatho, 2735',
    city: 'Mahikeng',
    province: 'North West',
    officeId: '',
    location: const GeoPoint(-25.8524, 25.6258),
  ),
  CourtModel(
    courtName: 'Northern Cape Division, Kimberley',
    courtLevel: 'High Court (Main Seat)',
    courtAddress: 'Sol Plaatje Drive, Kimberley, 8301',
    city: 'Kimberley',
    province: 'Northern Cape',
    officeId: '',
    location: const GeoPoint(-28.7397, 24.7644),
  ),
  CourtModel(
    courtName: 'Western Cape Division, Cape Town',
    courtLevel: 'High Court (Main Seat)',
    courtAddress: '35 Keerom Street, Cape Town, 8001',
    city: 'Cape Town',
    province: 'Western Cape',
    officeId: '',
    location: const GeoPoint(-33.9238, 18.4187),
  ),

  // --- Gauteng Magistrate's Courts ---
  CourtModel(
    courtName: 'Pretoria Magistrate\'s Court',
    courtLevel: 'Magistrate\'s Court',
    courtAddress: 'Cnr Sophie de Bruyn & Pretorius Streets, Pretoria, 0001',
    city: 'Pretoria',
    province: 'Gauteng',
    officeId: '',
    location: const GeoPoint(-25.7501, 28.1830),
  ),
  CourtModel(
    courtName: 'Pretoria North Magistrate\'s Court',
    courtLevel: 'Magistrate\'s Court',
    courtAddress: '335 Emily Hobhouse Avenue, Pretoria North, 0182',
    city: 'Pretoria',
    province: 'Gauteng',
    officeId: '',
    location: const GeoPoint(-25.6797, 28.1633),
  ),
  CourtModel(
    courtName: 'Mamelodi Magistrate\'s Court',
    courtLevel: 'Magistrate\'s Court',
    courtAddress: '19759 Sibande Street, Mamelodi East, Pretoria, 0122',
    city: 'Pretoria',
    province: 'Gauteng',
    officeId: '',
    location: const GeoPoint(-25.7237, 28.3619),
  ),
  CourtModel(
    courtName: 'Soshanguve Magistrate\'s Court',
    courtLevel: 'Magistrate\'s Court',
    courtAddress: '1975 Block H, Soshanguve, Pretoria, 0152',
    city: 'Pretoria',
    province: 'Gauteng',
    officeId: '',
    location: const GeoPoint(-25.5361, 28.0963),
  ),
  CourtModel(
    courtName: 'Ga-Rankuwa Magistrate\'s Court',
    courtLevel: 'Magistrate\'s Court',
    courtAddress: '1966 Setlogelo Street, Ga-Rankuwa, 0208',
    city: 'Ga-Rankuwa',
    province: 'Gauteng',
    officeId: '',
    location: const GeoPoint(-25.6179, 28.0016),
  ),
  CourtModel(
    courtName: 'Johannesburg Magistrate\'s Court (Central)',
    courtLevel: 'Magistrate\'s Court',
    courtAddress:
        'Cnr Ntemi Piliso & Fox Streets, Ferreirasdorp, Johannesburg, 2001',
    city: 'Johannesburg',
    province: 'Gauteng',
    officeId: '',
    location: const GeoPoint(-26.2072, 28.0335),
  ),
  CourtModel(
    courtName: 'Randburg Magistrate\'s Court',
    courtLevel: 'Magistrate\'s Court',
    courtAddress: '18 Shepherd Avenue, Randburg, 2194',
    city: 'Randburg',
    province: 'Gauteng',
    officeId: '',
    location: const GeoPoint(-26.0962, 28.0019),
  ),
  CourtModel(
    courtName: 'Soweto Magistrate\'s Court',
    courtLevel: 'Magistrate\'s Court',
    courtAddress:
        'Cnr Klipspruitvalley Rd & Armitage St, Orlando West, Soweto, 1804',
    city: 'Soweto',
    province: 'Gauteng',
    officeId: '',
    location: const GeoPoint(-26.2410, 27.9061),
  ),
  CourtModel(
    courtName: 'Alexandra Magistrate\'s Court',
    courtLevel: 'Magistrate\'s Court',
    courtAddress: 'Cnr 2nd Street & 8th Avenue, Alexandra, Sandton, 2090',
    city: 'Sandton',
    province: 'Gauteng',
    officeId: '',
    location: const GeoPoint(-26.1032, 28.0894),
  ),
  CourtModel(
    courtName: 'Roodepoort Magistrate\'s Court',
    courtLevel: 'Magistrate\'s Court',
    courtAddress: 'Cnr Rex & Meyer Streets, Roodepoort, 1724',
    city: 'Roodepoort',
    province: 'Gauteng',
    officeId: '',
    location: const GeoPoint(-26.1643, 27.8702),
  ),
  CourtModel(
    courtName: 'Booysens Magistrate\'s Court',
    courtLevel: 'Magistrate\'s Court',
    courtAddress:
        'Cnr Booysens Road & Garland Street, Booysens, Johannesburg, 2091',
    city: 'Johannesburg',
    province: 'Gauteng',
    officeId: '',
    location: const GeoPoint(-26.2325, 28.0264),
  ),
  CourtModel(
    courtName: 'Lenasia Magistrate\'s Court',
    courtLevel: 'Magistrate\'s Court',
    courtAddress: '1 Rose Avenue, Lenasia, Johannesburg, 1821',
    city: 'Johannesburg',
    province: 'Gauteng',
    officeId: '',
    location: const GeoPoint(-26.3195, 27.8443),
  ),
  CourtModel(
    courtName: 'Palm Ridge Magistrate\'s Court',
    courtLevel: 'Magistrate\'s Court',
    courtAddress: 'Cnr K146 & Palm Ridge Road, Palm Ridge, Alberton, 1458',
    city: 'Alberton',
    province: 'Gauteng',
    officeId: '',
    location: const GeoPoint(-26.3683, 28.1189),
  ),

  // --- Western Cape Magistrate's Courts ---
  CourtModel(
    courtName: 'Cape Town Magistrate\'s Court',
    courtLevel: 'Magistrate\'s Court',
    courtAddress: '7-11 Parade Street, Cape Town City Centre, Cape Town, 8001',
    city: 'Cape Town',
    province: 'Western Cape',
    officeId: '',
    location: const GeoPoint(-33.9264, 18.4253),
  ),
  CourtModel(
    courtName: 'Wynberg Magistrate\'s Court',
    courtLevel: 'Magistrate\'s Court',
    courtAddress: 'Cnr Church & Main Roads, Wynberg, Cape Town, 7800',
    city: 'Cape Town',
    province: 'Western Cape',
    officeId: '',
    location: const GeoPoint(-34.0016, 18.4682),
  ),
  CourtModel(
    courtName: 'Bellville Magistrate\'s Court',
    courtLevel: 'Magistrate\'s Court',
    courtAddress:
        'Cnr Jip de Jager Drive & Voortrekker Road, Bellville, Cape Town, 7530',
    city: 'Cape Town',
    province: 'Western Cape',
    officeId: '',
    location: const GeoPoint(-33.8872, 18.6367),
  ),
  CourtModel(
    courtName: 'Mitchells Plain Magistrate\'s Court',
    courtLevel: 'Magistrate\'s Court',
    courtAddress:
        'Cnr Ugwu & St Blaize Roads, Mitchells Plain Town Centre, Cape Town, 7785',
    city: 'Cape Town',
    province: 'Western Cape',
    officeId: '',
    location: const GeoPoint(-34.0450, 18.6200),
  ),
  CourtModel(
    courtName: 'Athlone Magistrate\'s Court',
    courtLevel: 'Magistrate\'s Court',
    courtAddress: 'Old Klipfontein Road, Athlone, Cape Town, 7764',
    city: 'Cape Town',
    province: 'Western Cape',
    officeId: '',
    location: const GeoPoint(-33.9575, 18.5080),
  ),
  CourtModel(
    courtName: 'Khayelitsha Magistrate\'s Court',
    courtLevel: 'Magistrate\'s Court',
    courtAddress:
        'Cnr Walter Sisulu Drive & Steve Biko Road, Khayelitsha, Cape Town, 7784',
    city: 'Cape Town',
    province: 'Western Cape',
    officeId: '',
    location: const GeoPoint(-34.0435, 18.6738),
  ),
  CourtModel(
    courtName: 'Atlantis Magistrate\'s Court',
    courtLevel: 'Magistrate\'s Court',
    courtAddress: 'Civic Centre, Reygersdal Drive, Atlantis, 7349',
    city: 'Atlantis',
    province: 'Western Cape',
    officeId: '',
    location: const GeoPoint(-33.5684, 18.4907),
  ),
  CourtModel(
    courtName: 'Kuils River Magistrate\'s Court',
    courtLevel: 'Magistrate\'s Court',
    courtAddress: '122 Van Riebeeck Road, Kuils River, Cape Town, 7580',
    city: 'Cape Town',
    province: 'Western Cape',
    officeId: '',
    location: const GeoPoint(-33.9312, 18.6806),
  ),
  CourtModel(
    courtName: 'Goodwood Magistrate\'s Court',
    courtLevel: 'Magistrate\'s Court',
    courtAddress:
        'Cnr Voortrekker Road & Hugo Street, Goodwood, Cape Town, 7460',
    city: 'Cape Town',
    province: 'Western Cape',
    officeId: '',
    location: const GeoPoint(-33.9015, 18.5528),
  ),
  CourtModel(
    courtName: 'Somerset West Magistrate\'s Court',
    courtLevel: 'Magistrate\'s Court',
    courtAddress: '24 Andries Pretorius Street, Somerset West, 7130',
    city: 'Somerset West',
    province: 'Western Cape',
    officeId: '',
    location: const GeoPoint(-34.0818, 18.8504),
  ),
  CourtModel(
    courtName: 'Simon\'s Town Magistrate\'s Court',
    courtLevel: 'Magistrate\'s Court',
    courtAddress: '88 St George\'s Street, Simon\'s Town, Cape Town, 7995',
    city: 'Cape Town',
    province: 'Western Cape',
    officeId: '',
    location: const GeoPoint(-34.1925, 18.4312),
  ),
  CourtModel(
    courtName: 'Strand Magistrate\'s Court',
    courtLevel: 'Magistrate\'s Court',
    courtAddress: 'Cnr Fagan & De Villiers Streets, Strand, 7140',
    city: 'Strand',
    province: 'Western Cape',
    officeId: '',
    location: const GeoPoint(-34.1129, 18.8315),
  ),
  CourtModel(
    courtName: 'Philippi Magistrate\'s Court',
    courtLevel: 'Magistrate\'s Court',
    courtAddress: '121 Stock Road, Philippi, Cape Town, 7750',
    city: 'Cape Town',
    province: 'Western Cape',
    officeId: '',
    location: const GeoPoint(-33.9934, 18.5446),
  ),
  CourtModel(
    courtName: 'Bishop Lavis Magistrate\'s Court',
    courtLevel: 'Magistrate\'s Court',
    courtAddress: '80 Owen Road, Bishop Lavis, Cape Town, 7490',
    city: 'Cape Town',
    province: 'Western Cape',
    officeId: '',
    location: const GeoPoint(-33.9366, 18.5835),
  ),

  // --- KwaZulu-Natal Magistrate's Courts ---
  CourtModel(
    courtName: 'Durban Magistrate\'s Court',
    courtLevel: 'Magistrate\'s Court (Main Seat)',
    courtAddress: 'Cnr Somtseu & Stalwart Simelane Streets, Durban, 4001',
    city: 'Durban',
    province: 'KwaZulu-Natal',
    officeId: '',
    location: const GeoPoint(-29.8497, 31.0264),
  ),
  CourtModel(
    courtName: 'Pinetown Magistrate\'s Court',
    courtLevel: 'Magistrate\'s Court',
    courtAddress: '5 Chancery Lane, Pinetown, 3610',
    city: 'Pinetown',
    province: 'KwaZulu-Natal',
    officeId: '',
    location: const GeoPoint(-29.8159, 30.8524),
  ),
  CourtModel(
    courtName: 'Verulam Magistrate\'s Court',
    courtLevel: 'Magistrate\'s Court',
    courtAddress: '52 George Sewpersadh Street, Verulam, 4340',
    city: 'Verulam',
    province: 'KwaZulu-Natal',
    officeId: '',
    location: const GeoPoint(-29.6450, 31.0505),
  ),
  CourtModel(
    courtName: 'Chatsworth Magistrate\'s Court',
    courtLevel: 'Magistrate\'s Court',
    courtAddress: '1 Justice Street, Chatsworth Town Centre, Chatsworth, 4092',
    city: 'Chatsworth',
    province: 'KwaZulu-Natal',
    officeId: '',
    location: const GeoPoint(-29.9125, 30.9169),
  ),
  CourtModel(
    courtName: 'Umlazi Magistrate\'s Court',
    courtLevel: 'Magistrate\'s Court',
    courtAddress: '1 Griffiths Mxenge Highway, Umlazi V, Umlazi, 4060',
    city: 'Umlazi',
    province: 'KwaZulu-Natal',
    officeId: '',
    location: const GeoPoint(-29.9575, 30.8920),
  ),
  CourtModel(
    courtName: 'Ntuzuma Magistrate\'s Court',
    courtLevel: 'Magistrate\'s Court',
    courtAddress:
        '88 Bridge City Boulevard, Phoenix Industrial Park, Ntuzuma, 4310',
    city: 'Ntuzuma',
    province: 'KwaZulu-Natal',
    officeId: '',
    location: const GeoPoint(-29.7423, 30.9705),
  ),
  CourtModel(
    courtName: 'Umbumbulu Magistrate\'s Court',
    courtLevel: 'Magistrate\'s Court',
    courtAddress: 'District Road 446, Umbumbulu, 4105',
    city: 'Umbumbulu',
    province: 'KwaZulu-Natal',
    officeId: '',
    location: const GeoPoint(-30.0716, 30.7061),
  ),
  CourtModel(
    courtName: 'Wentworth Magistrate\'s Court',
    courtLevel: 'Magistrate\'s Court (Branch)',
    courtAddress: '1 Austerville Drive, Wentworth, Durban, 4052',
    city: 'Durban',
    province: 'KwaZulu-Natal',
    officeId: '',
    location: const GeoPoint(-29.9169, 31.0094),
  ),
  CourtModel(
    courtName: 'Amanzimtoti Magistrate\'s Court',
    courtLevel: 'Magistrate\'s Court (Branch)',
    courtAddress: '1 Nelson Road, Amanzimtoti, 4126',
    city: 'Amanzimtoti',
    province: 'KwaZulu-Natal',
    officeId: '',
    location: const GeoPoint(-30.0526, 30.8872),
  ),
  CourtModel(
    courtName: 'Tongaat Magistrate\'s Court',
    courtLevel: 'Magistrate\'s Court (Branch)',
    courtAddress: '318 Gopalall Hurbans Road, Tongaat, 4400',
    city: 'Tongaat',
    province: 'KwaZulu-Natal',
    officeId: '',
    location: const GeoPoint(-29.5750, 31.1272),
  ),
];
