import 'package:cloud_firestore/cloud_firestore.dart';
import 'package:fastcorr_shared/utils/utils.dart';

class SheriffModel {
  final String? sheriffName;
  final String? magisterialDistrict;
  final String? address;
  final String? postalAddress;
  final String? officeLine;
  final String? cellNumber;
  final String? emailAddress;
  final String? province;
  final String? postalCode;

  SheriffModel({
    this.sheriffName,
    this.magisterialDistrict,
    this.address,
    this.postalAddress,
    this.officeLine,
    this.cellNumber,
    this.emailAddress,
    this.province,
    this.postalCode,
  });

  Map<String, dynamic> toJson() {
    return {
      'sheriffName': sheriffName,
      'magisterialDistrict': magisterialDistrict,
      'address': address,
      'postalAddress': postalAddress,
      'officeLine': officeLine,
      'cellNumber': cellNumber,
      'emailAddress': emailAddress,
      'province': province,
      'postalCode': postalCode,
    };
  }

  // Factory constructor to create a Sheriff object from a Map (JSON)
  factory SheriffModel.fromJson(Map<String, dynamic> json) {
    return SheriffModel(
      sheriffName: cleanString(json['Sheriff Name']),
      magisterialDistrict: cleanString(json['Magisterial District (HL)']),
      address: cleanString(json['Address']),
      postalAddress: cleanString(json['Postal Address']),
      officeLine: cleanString(json['Office Line 1']),
      cellNumber: cleanString(json['Cell Number']),
      emailAddress: cleanString(json['Email Address']),
      province: cleanString(json['Province']),
      postalCode: cleanString(json['Postal Code']),
    );
  }

  factory SheriffModel.fromSnapshot(DocumentSnapshot snap) {
    return SheriffModel(
      sheriffName: cleanString(snap['Sheriff Name']),
      magisterialDistrict: cleanString(snap['Magisterial District (HL)']),
      address: cleanString(snap['Address']),
      postalAddress: cleanString(snap['Postal Address']),
      officeLine: cleanString(snap['Office Line 1']),
      cellNumber: cleanString(snap['Cell Number']),
      emailAddress: cleanString(snap['Email Address']),
      province: cleanString(snap['Province']),
      postalCode: cleanString(snap['Postal Code']),
    );
  }

  List<SheriffModel> sheriffList = [
    SheriffModel(
      sheriffName: 'Ms Babalwa Primrose Konjwa',
      magisterialDistrict: 'Molteno HL',
      address: '79 Smith Street, Molteno, South Africa, 5500',
      postalAddress: 'P.O. Box 127, Molteno, 5500',
      cellNumber: '072-177-9736',
      emailAddress: 'konjwabp@gmail.com',
      province: 'Eastern Cape',
      postalCode: '5500',
    ),
    SheriffModel(
      sheriffName: 'Mr Gcobani Mkwakwa',
      magisterialDistrict: 'Cradock HL',
      address: '55 Jacaranda Street, Lusikisiki, South Africa, 4820',
      postalAddress: 'P.O. Box 785, Cradock, 5880',
      officeLine: '048-881-0213',
      cellNumber: '076-223-0711',
      emailAddress: 'sheriffcradock@telkomsa.net',
      province: 'Eastern Cape',
      postalCode: '5880',
    ),

    SheriffModel(
      sheriffName: 'Ms Jennifer Lynne Coetzer',
      magisterialDistrict: 'Stutterheim HL',
      address: '57 Komani Street, Queenstown, 5320',
      postalAddress: '57 Komani Street, Queenstown, 5320',
      officeLine: '045-838-4242',
      cellNumber: '082-337-3749',
      emailAddress: 'jenny.queenstownsheriff@nokwi.co.za',
      province: 'Eastern Cape',
      postalCode: '5320',
    ),

    SheriffModel(
      sheriffName: 'Mr Johan Rigardt Nieuwenhuizen',
      magisterialDistrict: 'Steynsburg HL',
      address: '27 Middle Street Manor, Graaff-Reinet, South Africa, 6280',
      postalAddress: 'P.O. Box 70, Graaff-Reinet, 6280',
      officeLine: '049-891-0213',
      cellNumber: '082-881-1003',
      emailAddress: 'sheriffrn@gmail.com',
      province: 'Western Cape',
      postalCode: '6280',
    ),
    SheriffModel(
      sheriffName: 'Mr Luvuyo Jeffery Leshosi',
      magisterialDistrict: 'Somerset East HL',
      address:
          '10 Nojoli Street, Pep Stores Building, Flat 2, Somerset East, South Africa, 5850',
      postalAddress: 'P.O. Box 254, Somerset East, 5850',
      officeLine: '042-243-0106',
      cellNumber: '078-145-5066',
      emailAddress: 'sheriffsse1@gmail.com',
      province: 'Eastern Cape',
      postalCode: '5850',
    ),

    SheriffModel(
      sheriffName: 'Mr Mbongeni George',
      magisterialDistrict: 'Mqanduli HL',
      address:
          '71 Cumberland Street, Umtata Central, Mthatha, South Africa, 5100',
      postalAddress: '71 Cumberland Street, Mthatha, 5099',
      officeLine: '047-110-9124',
      cellNumber: '068-313-4264',
      emailAddress: 'jandasiqibo8@gamil.com',
      province: 'Eastern Cape',
      postalCode: '5100',
    ),
    SheriffModel(
      sheriffName: 'Mrs Nokwanda Tandeka Patricia Nyabaza',
      magisterialDistrict: 'Engcobo HL',
      address: '122 Sutherland Street CNR Blakeway Road, Mthatha, 5099',
      postalAddress: 'P.O. Box 195, Engcobo, 5050',
      officeLine: '047-050-2497',
      cellNumber: '082-671-0332',
      emailAddress: 'staff.mthathalowecourt@outlook.com',
      province: 'Eastern Cape',
      postalCode: '5100; 5050',
    ),

    SheriffModel(
      sheriffName: 'Ms Nomajwara Victoria Soga',
      magisterialDistrict: 'Port Elizabeth West HL',
      address:
          '68 Perkins Street, North End, Gqeberha, Port Elizabeth, South Africa, 6001',
      province: 'Eastern Cape',
      postalCode: '6001',
    ),
    SheriffModel(
      sheriffName: 'Mr RS Wentzel',
      magisterialDistrict: 'Alice HL',
      address: '2 Canna Street, Newtown, Fort Beaufort, South Africa, 5720',
      postalAddress: 'P.O. Box 200, Fort Beaufort, 5720',
      cellNumber: '071-283-4427',
      province: 'Eastern Cape',
      postalCode: '5720',
    ),
    SheriffModel(
      sheriffName: 'Ms Pakama Mlandu',
      magisterialDistrict: 'Maluti HL',
      address: '86 High Street, Matatiele, 4730',
      postalAddress: 'P.O. Box 181, Matatiele, 4730',
      cellNumber: '073-611-2090',
      emailAddress: 'pakama@sheriffmlandu.co.za',
      province: 'Kwa-Zulu Natal',
      postalCode: '4700',
    ),
    SheriffModel(
      sheriffName: 'Ms Pakama Mlandu',
      magisterialDistrict: 'Lady Grey HL',
      address: '72 Smith Street, Aliwal North, 9750',
      postalAddress: 'P.O. Box 397, Aliwal North, 9750',
      cellNumber: '073-611-2090',
      emailAddress: 'pakama@sheriffmlandu.co.za',
      province: 'Eastern Cape',
      postalCode: '9750',
    ),
    SheriffModel(
      sheriffName: 'Mr Ngwako Archibald Sekhula',
      magisterialDistrict: 'Nkowankowa HL',
      address:
          'Office no 204, 1 Bankuna Street, Leda Regional Office, Nkowankowa, 0870',
      officeLine: '015-000-6199',
      province: 'Limpopo',
      postalCode: '0870',
    ),
    SheriffModel(
      sheriffName: 'Mr Lesiba Elias Klerksdorp',
      magisterialDistrict: 'Boshof HL',
      address: '43 Coetzee Street, Zeerust, South Africa, 2865',
      postalAddress: 'P.O. Box 1049, Bochum, 0790',
      officeLine: '015-004-1565',
      emailAddress: 'shefbochum@gmail.com',
      province: 'Limpopo',
      postalCode: '2865',
    ),
    SheriffModel(
      sheriffName: 'Mr M Monyamane',
      magisterialDistrict: 'Bela-Bela HL',
      address: '78 Beckett Street, Bela-Bela, 0480',
      postalAddress: 'P.O. Box 168, Bela-Bela, 0480',
      officeLine: '014-736-3061',
      cellNumber: '079-963-0746',
      emailAddress: 'sheriffbelabela@gmail.com',
      province: 'Limpopo',
      postalCode: '0480',
    ),
    SheriffModel(
      sheriffName: 'Ms Meggie Sebotsa Phiri',
      magisterialDistrict: 'Hlanganani HL',
      address:
          'Quick Save Plaza, Office B9, Malamulele, Next to Malamulele Magistrate Court, 0982',
      postalAddress: 'P.O. Box 1405, Tzaneen, 0850',
      cellNumber: '079-443-1415',
      province: 'Limpopo',
      postalCode: '0982',
    ),
    SheriffModel(
      sheriffName: 'Ms Meggie Sebotsa Phiri',
      magisterialDistrict: 'Sekgosese HL',
      address:
          'Quick Save Plaza, Office B9, Malamulele, Next to Malamulele Magistrate Court, 0982',
      officeLine: '015-004-2022',
      cellNumber: '079-443-1415',
      emailAddress: 'sheriffmapulaneng@gmail.com',
      province: 'Limpopo',
      postalCode: '0982',
    ),
    SheriffModel(
      sheriffName: 'Ms Ponto Carol Shai',
      magisterialDistrict: 'Mhalala HL',
      address:
          'Legal Chambers, Office No 02, Manyeleti Main Road, Acorn Hoek, 1360',
      postalAddress: 'Legal Chambers, Office No 02, Acorn Hoek, 1360',
      cellNumber: '079-443-1415',
      province: 'Limpopo',
      postalCode: '1360',
    ),
    SheriffModel(
      sheriffName: 'Mr Ronald Tshisamphiri Mapfumo',
      magisterialDistrict: 'Mutale H',
      address: '2/521 Tshilamba, Freedom Street, Thohoyandou, Limpopo, 0956',
      postalAddress: 'P.O. Box 84, Mutale, 0956',
      officeLine: '082-476-9442',
      cellNumber: '082-476-9442',
      emailAddress: 'mutalesheriff@gmail.com',
      province: 'Limpopo',
      postalCode: '0956',
    ),
    SheriffModel(
      sheriffName: 'Mr Nkosinathi Simphiwe Dlamini',
      magisterialDistrict: 'Umlazi HL',
      address: '37 Malamba Road, Old Magistrate Court, Block C. Room 4, 4089',
      postalAddress: 'P.O. Box 37889, Overport, 4089',
      officeLine: '031-906-1713',
      emailAddress: 'nsdsheriff@gmail.com',
      province: 'KwaZulu-Natal',
      postalCode: '4089',
    ),
    SheriffModel(
      sheriffName: 'Mr MB Zwedala',
      magisterialDistrict: 'Carnarvon HL',
      address: '12 Barnard Street, Victoria West, 7070',
      postalAddress: 'P.O. Box 219, Victoria West, 7070',
      officeLine: '078-881-2065',
      cellNumber: '063-230-0657',
      emailAddress: 'vwskeriff1@gmail.com',
      province: 'Northern Cape',
      postalCode: '7070',
    ),
    SheriffModel(
      sheriffName: 'Mrs Magda Moorcroft',
      magisterialDistrict: 'Gordonia (Upington) HL',
      address: '1/31 Schoeman Street, Upington, South Africa, 8801',
      postalAddress: 'P.O. Box 1065, Upington, 8800',
      officeLine: '078-866-2469',
      emailAddress: 'moorcroftmagda@yahoo.com',
      province: 'Northern Cape',
      postalCode: '8801',
    ),
    SheriffModel(
      sheriffName: 'Mr Madiba Hopney Makgwana',
      magisterialDistrict: 'Kathu HL',
      address:
          'Shop 8, Shoprite Centre, Rietbok Street, Kathu, South Africa, 8446',
      postalAddress: 'P.O. Box 1708, Zeerust, 2865',
      cellNumber: '072-647-7330',
      emailAddress: 'mphmakgwana@gmail.com',
      province: 'Northern Cape',
      postalCode: '8446',
    ),
    SheriffModel(
      sheriffName: 'Mrs Martha J Brooks',
      magisterialDistrict: 'Griekwastad HL',
      address: '18a Naauw street, Prieska, South Africa, 8940',
      postalAddress: '18 A Naauw Street, Prieska, 8940',
      officeLine: '072-310-4950',
      emailAddress: 'prieskabalu@gmail.com',
      province: 'Northern Cape',
      postalCode: '8940',
    ),
    SheriffModel(
      sheriffName: 'Mr Sebelo Witness Ntshokoma',
      magisterialDistrict: 'Peddie HL',
      address: '1277 Albert Street, Gwavu Complex, Peddie South Africa, 5640',
      cellNumber: '078-782-8581',
      province: 'Eastern Cape',
      postalCode: '6139',
    ),
    SheriffModel(
      sheriffName: 'Mr Christian Hattingh De Wet',
      magisterialDistrict: 'Bloemfontein West HL',
      address: '6A 3rd Street, Arboreturm, Bloemfontein, South Africa, 9301',
      postalAddress: 'P.O. Box 3720, Bloemfontein, 9300',
      officeLine: '051-430-1011',
      cellNumber: '083-270-4965',
      emailAddress: 'bfnwest@sheriffnet.co.za',
      province: 'Free State',
      postalCode: '9301',
    ),
    SheriffModel(
      sheriffName: 'Mr Clayton Peter Brown',
      magisterialDistrict: 'Welkom HL',
      address: '366 Stateway, Doorn, Welkom, South Africa, 9459',
      postalAddress: 'P.O. Box 1500, Welkom, 9460',
      officeLine: '057-352-1927',
      cellNumber: '065-867-2104',
      emailAddress: 'admin@sutu.co.za',
      province: 'Free State',
      postalCode: '9459',
    ),
    SheriffModel(
      sheriffName: 'Mrs Isobel Du Plessis',
      magisterialDistrict: 'Morgenzon L',
      address: '51A Dr Beyers Naude Street, Standerton, 2430',
      postalAddress: 'P.O. Box 600, Standerton, 2430',
      officeLine: '017-712-4299',
      emailAddress: 'Elbiedp@vodamail.co.za',
      province: 'Mpumalanga',
      postalCode: '2430',
    ),
    SheriffModel(
      sheriffName: 'Mr Ivan Roy Swart',
      magisterialDistrict: 'Balfour HL',
      address: '40 Mare Street, Heidelberg, 1441',
      postalAddress: 'P.O. Box 1006, Delmas, 2210',
      officeLine: '064-807-3093',
      emailAddress: 'sherifheidlebalfour@gmail.com',
      province: 'Gauteng',
      postalCode: '1441',
    ),
    SheriffModel(
      sheriffName: 'Mr Martin Akker',
      magisterialDistrict: 'Belfast H',
      address: '16 Smit Street, Belfast, South Africa, 1100',
      postalAddress: 'P.O. Box 666, Belfast, 1100',
      officeLine: '072-365-0963',
      province: 'Mpumalanga',
      postalCode: '1100',
    ),
    SheriffModel(
      sheriffName: 'Mr Stemmer Johannes Mahamba',
      magisterialDistrict: 'Bethal HL',
      address: '28 Vuyisile Mini Street, Bethal, 2310',
      postalAddress: 'P.O. Box 15, Bethal, 2310',
      officeLine: '079-784-8423',
      province: 'Mpumalanga',
      postalCode: '2310',
    ),
    SheriffModel(
      sheriffName: 'Mr Thabiso Anthony Mtsweni',
      magisterialDistrict: 'Kwa-Lugedlane HL',
      address: '36 Fitzgerald Street, 3 Kwelanga Accommodation, Belfast, 1100.',
      postalAddress: 'Private Bag X4026, Kwa-Lugedlane, 1341',
      officeLine: '013-170-5903',
      cellNumber: '082-586-5563',
      province: 'Mpumalanga',
      postalCode: '1341',
    ),
    SheriffModel(
      sheriffName: 'Mr Siyabonga Maxwell Nxumalo',
      magisterialDistrict: 'KwaMhlanga L',
      address:
          'Solomon Mahlangu Drive, 110BA Medical Centre, Kwamhlanga, South Africa, 1022',
      postalAddress: 'P.O. Box 83, Carolina, 1185',
      officeLine: '071-873-9058',
      cellNumber: '071-873-5649',
      emailAddress: 'admin@sheriffcal.co.za',
      province: 'Mpumalanga',
      postalCode: '1022',
    ),
    SheriffModel(
      sheriffName: 'Mrs Anna Magrieta Erasmus',
      magisterialDistrict: 'Randfontein HL',
      address:
          'Old ABSA Building, CNR Kruger & Human Streets, Krugersdorp, 1740',
      postalAddress: 'P.O. Box 364, Randfontein, 1760',
      officeLine: '010-534-9351',
      emailAddress: 'Nthabiseng@sheriffrandfontein.co.za',
      province: 'Gauteng',
      postalCode: '1739',
    ),
    SheriffModel(
      sheriffName: 'Mr Ian Burton',
      magisterialDistrict: 'Alberton North HL',
      address: 'No 31 Leslie Street, Vereeniging, 2000',
      postalAddress: 'P.O. Box 157, Alberton, 1450',
      officeLine: '011-907-1040',
      province: 'Gauteng',
      postalCode: '1450',
    ),
    SheriffModel(
      sheriffName: 'Mr Owen Khumalo',
      magisterialDistrict: 'Roodepoort North HL',
      address: 'No 31 Leslie Street, Vereeniging, 2000',
      postalAddress: 'P.O. Box 157, Alberton, 1450',
      officeLine: '011-907-1040',
      province: 'Gauteng',
      postalCode: '1450',
    ),
    SheriffModel(
      sheriffName: 'Ms Mmankwe Ancilia Blantina Mahlangu',
      magisterialDistrict: 'Centurion West HL',
      address: '22 Voortrekker Street, Edenvale, 1600',
      postalAddress: 'P.O. Box 2487, Lyttleton, 0140',
      officeLine: '012-663-8344',
      cellNumber: '076-943-4663',
      province: 'Gauteng',
      postalCode: '1600',
    ),
    SheriffModel(
      sheriffName: 'Mr Ken Rwaan Steven Abrahams',
      magisterialDistrict: 'Nigel HL',
      address: '74 Von Geusau Street, Nigel, 1490',
      postalAddress: 'P.O. Box 470, Nigel, 1490',
      officeLine: '011-814-1111',
      cellNumber: '083-261-2486',
      emailAddress: 'sheriffrandburgsw.com',
      province: 'Gauteng',
      postalCode: '1490',
    ),
    SheriffModel(
      sheriffName: 'Mr Pramodh Ora',
      magisterialDistrict: 'Vanderbijlpark HL',
      address: 'Lamees Building, 20 Hertz Boulevard, Vanderbijlpark, 1900',
      postalAddress: 'P.O. Box 201, Vanderbijlpark HL, 1900',
      officeLine: '016-100-7942',
      emailAddress: 'Info@sheriffvanderbijlpark.co.za',
      province: 'Gauteng',
      postalCode: '1900',
    ),
    SheriffModel(
      sheriffName: 'Mr Indran Adimoolum',
      magisterialDistrict: 'Boksburg HL',
      address: 'Unit 1/1, Office Park, 27 Rietfontein Rd, Boksburg, 1459',
      postalAddress: 'P.O. Box 550, Boksburg, 1460',
      officeLine: '011-892-2840',
      cellNumber: '082-873-1002',
      emailAddress: 'sheriffboksburg@telkomsa.net',
      province: 'Gauteng',
      postalCode: '1459',
    ),
    SheriffModel(
      sheriffName: 'Mr Siphesihle Lansloe Ngcobo',
      magisterialDistrict: 'Greytown HL',
      address: '65 Maitland Road, R.A. Centre, Office No 17, 3250',
      postalAddress: 'P.O. Box 332, Greytown, 3250',
      province: 'Kwa-Zulu Natal',
      postalCode: '3250',
    ),
    SheriffModel(
      sheriffName: 'Mr Rishaad Singh',
      magisterialDistrict: 'Lower Tugela (Stanger) HL',
      address:
          'Suite 3, Prithivi Centre, 131 Mahatma Ghandi Street, KwaDukuza, 4449',
      postalAddress: 'P.O. Box 80, KwaDukuza, 4449',
      province: 'KwaZulu-Natal',
      postalCode: '4449',
    ),
    SheriffModel(
      sheriffName: 'Mrs Adelaide Miswe Mzimela',
      magisterialDistrict: 'Pietermaritzburg L',
      address: '20 Otto Street, Pietermaritzburg, 3201',
      postalAddress: 'P.O. Box 548, Pietermaritzburg, 3201',
      officeLine: '033-394-5207',
      cellNumber: '064-889-8540',
      emailAddress: 'sheriffrichmond6@gmail.com',
      province: 'Kwa-Zulu Natal',
      postalCode: '3201',
    ),
    SheriffModel(
      sheriffName: 'Mr Bhoyi Simon Mpungose',
      magisterialDistrict: 'Ingwavuma HL',
      address: 'Lot 457, Nongoma, Ingwavuma, South Africa, 3950',
      postalAddress: 'P.O. Box 202, Nongoma, 3950',
      cellNumber: '083-248-6300',
      emailAddress: 'sheriff.ingwavuma@gmail.com',
      province: 'Kwa-Zulu Natal',
      postalCode: '3950',
    ),
    SheriffModel(
      sheriffName: 'Ms Maureen Nozindaba Cibe',
      magisterialDistrict: 'Soweto West HL',
      address: '2241 Nkopi & Rasmeni Street, Protea North, 1818',
      postalAddress: 'P.O. Box 656, Lenasia, 1820',
      officeLine: '011-980-6681',
      cellNumber: '082-700-9281',
      emailAddress: 'admin@sheriffsowetowest.co.za',
      province: 'Gauteng',
      postalCode: '1815',
    ),
    SheriffModel(
      sheriffName: 'Mr Gerald Daniel Itumeleng Malao',
      magisterialDistrict: 'Tlokwe (Potchefstroom) HL',
      address: 'No. 8 Luke Street, Potchefstroom, 2531',
      postalAddress: 'No. 8 Luke Street, Potchefstroom, 2531',
      officeLine: '067-375-2812',
      emailAddress: 'admin@sheriffpotch.co.za',
      province: 'North West',
      postalCode: '2531',
    ),
    SheriffModel(
      sheriffName: 'Mr Wynaand Frederick Minnie',
      magisterialDistrict: 'Reitz HL',
      address: '22 De Wet Street, Reitz, South Africa, 9810',
      postalAddress: 'P.O. Box 283, Reitz, 9810',
      officeLine: '083-654-7512',
      emailAddress: 'sheriffreitz@gmail.com',
      province: 'Free State',
      postalCode: '9810',
    ),
    SheriffModel(
      sheriffName: 'Mr Bothata Mosikili',
      magisterialDistrict: 'Wesselsbron HL',
      address: '2 Nygella Gardens, Virginia, South Africa, 9430',
      postalAddress: 'P.O. Box 80, Virginia, 9430',
      officeLine: '057-212-0271',
      cellNumber: '073-308-6481',
      emailAddress: 'mosikili@ymail.com',
      province: 'Free State',
      postalCode: '9431',
    ),

    SheriffModel(
      sheriffName: 'Mr Molifi Aaron Matsoso',
      magisterialDistrict: 'Dewetsdorp HL & Wepener HL',
      address:
          '44 Andries Pretorius Street, 5 Ulandi Hof, Theunissen, South Africa, 9410',
      postalAddress: 'P.O. Box 87, Theunissen, 9410',
      officeLine: '057-733-0019',
      cellNumber: '060-373-4720',
      emailAddress: 'sherifftheunissen@gmail.com',
      province: 'Free State',
      postalCode: '9410',
    ),

    SheriffModel(
      sheriffName: 'Mrs Kelebogile Maria Magdaleena Mpe',
      magisterialDistrict: 'Bfn North L',
      address: '2 Borister Street, Kimberley North, Kimberley, 8300',
      postalAddress: 'P.O. Box 230, Bloemfontein, 9300',
      officeLine: '051-447-3784',
      emailAddress: 'sheriff@sheriffbfne.co.za',
      province: 'Free State',
      postalCode: '8300',
    ),
    SheriffModel(
      sheriffName: 'Mr Pule Klaas Foka',
      magisterialDistrict: 'Makwane HL',
      address: '3030 De Bult, Phuthaditjhaba, South Africa, 9869',
      postalAddress: 'P.O. Box 5465, Phuthaditjhaba, 9866',
      officeLine: '058-713-0702',
      cellNumber: '082-212-5350',
      province: 'Free State',
      postalCode: '9869',
    ),
    SheriffModel(
      sheriffName: 'Mr Pule Klaas Foka',
      magisterialDistrict: 'Tseke HL',
      address: 'Phuthaditjhaba, South Africa',
      postalAddress: 'P.O. Box 5465, Phuthaditjhaba, 9866',
      officeLine: '058-713-0702',
      cellNumber: '082-212-5350',
      province: 'Free State',
      postalCode: '9869',
    ),
    SheriffModel(
      sheriffName: 'Mrs Thabisile Geraldine Khumalo',
      magisterialDistrict: 'Thabanchu HL',
      address: '5 Reitz Street, Thaba Nchu, South Africa, 9780',
      postalAddress: 'P.O. Box 26, Thabanchu, 9780',
      officeLine: '051-875-1760',
      cellNumber: '079-442-6397',
      emailAddress: 'sheriffbt@sheriffnet.co.za',
      province: 'Free State',
      postalCode: '9780',
    ),
    SheriffModel(
      sheriffName: 'Mrs Kelebogile Maria Magdaleena Mpe',
      magisterialDistrict: 'Kimberley HL',
      address: '2 Borister Street, Kimberley North, Kimberley, 8300',
      postalAddress: 'P.O. Box 230, Bloemfontein, 9300',
      officeLine: '051-447-3784',
      emailAddress: 'sheriff@sheriffbfne.co.za',
      province: 'Northern Cape',
      postalCode: '8300',
    ),
    SheriffModel(
      sheriffName: 'Mrs Magda Moorcroft',
      magisterialDistrict: 'Upington L',
      address: '1/31 Schoeman Street, Upington, South Africa, 8801',
      postalAddress: 'P.O. Box 1065, Upington, 8800',
      officeLine: '078-866-2469',
      emailAddress: 'moorcroftmagda@yahoo.com',
      province: 'Northern Cape',
      postalCode: '8801',
    ),
    SheriffModel(
      sheriffName: 'Mr Madiba Hopney Makgwana',
      magisterialDistrict: 'Postmasburg (Olifantshoek) HL',
      address:
          'Shop 8, Shoprite Centre, Rietbok Street, Kathu, South Africa, 8446',
      postalAddress: 'P.O. Box 1708, Zeerust, 2865',
      cellNumber: '072-647-7330',
      emailAddress: 'mphmakgwana@gmail.com',
      province: 'Northern Cape',
      postalCode: '8446',
    ),
    SheriffModel(
      sheriffName: 'Mrs Martha J Brooks',
      magisterialDistrict: 'Douglas HL',
      address: '18a Naauw street, Prieska, South Africa, 8940',
      officeLine: '072-310-4950',
      emailAddress: 'prieskabalu@gmail.com',
      province: 'Northern Cape',
      postalCode: '8940',
    ),
    SheriffModel(
      sheriffName: 'Mrs Amanda Junita Laetitia Titus',
      magisterialDistrict: 'Somerset West HL',
      address: 'Shop 1 Twin Oaks Centre, 144 Main Road, Somerset West, 7130',
      postalAddress: 'P.O. Box 696, Cape Town, 8000',
      officeLine: '060-966-8422',
      cellNumber: '072-644-6888',
      emailAddress: 'admin@sheriffsw.co.za',
      province: 'Western Cape',
      postalCode: '7130',
    ),
    SheriffModel(
      sheriffName: 'Mr Andrew Kgopolo Nkhumise',
      magisterialDistrict: 'Paarl HL',
      address: '12 Castle Street, Paarl, 7646',
      postalAddress: 'P.O. Box 856, Paarl, 7620',
      officeLine: '021-863-1250',
      cellNumber: '082-959-8664',
      emailAddress: 'sheriffpaarl@gmail.com',
      province: 'Western Cape',
      postalCode: '7646',
    ),
    SheriffModel(
      sheriffName: 'Mr Adrian Reginald Cupido',
      magisterialDistrict: 'Oudtshoorn HL',
      address:
          '9 Cnr Plume Street & Tabak Street, Oudtshoorn, South Africa, 6625',
      postalAddress: 'P.O. Box 802, Oudtshoorn, 6620',
      officeLine: '044-279-1127',
      cellNumber: '071-225-3187',
      emailAddress: 'sheriff.cupido@gmail.com',
      province: 'Western Cape',
      postalCode: '6625',
    ),
    SheriffModel(
      sheriffName: 'Mr Barend Johannes Geldenhuys',
      magisterialDistrict: 'Moorreesburg HL',
      address: '4 Meul Street, Moorreesburg, South Africa, 7310',
      postalAddress: 'P.O. Box 102, Moorreesburg, 7310',
      officeLine: '022-433-2815',
      cellNumber: '082-446-2815',
      emailAddress: 'bjgeldenhuys@telkomsa.net',
      province: 'Western Cape',
      postalCode: '7310',
    ),
    SheriffModel(
      sheriffName: 'Mr Pieter Ricardo John Hull',
      magisterialDistrict: 'Strand HL',
      address: '9 Theale Street, Strand, 7139',
      postalAddress: 'P.O. Box 218, Strand, 7139',
      officeLine: '021-853-7436',
      emailAddress: 'strand@sheriffnet.co.za',
      province: 'Western Cape',
      postalCode: '7139',
    ),
    SheriffModel(
      sheriffName: 'Mr Francois Van Greunen',
      magisterialDistrict: 'Elsies Rivier HL',
      address:
          'Unit B5 Coleman Industrial Park, Coleman Street, Elsies River, 7451',
      postalAddress: 'P.O. Box 71, Sanlamhof, 7532',
      officeLine: '021-931-8255',
      cellNumber: '082-824-2139',
      emailAddress: 'sherifelsiesrivier@gmail.com',
      province: 'Western Cape',
      postalCode: '7451',
    ),
    SheriffModel(
      sheriffName: 'Mr Michiel Smith Basson',
      magisterialDistrict: 'Malmesbury HL',
      address: '11 St John St, Malmesbury, South Africa, 7300',
      postalAddress: 'P.O. Box 704, Malmesbury, 7299',
      officeLine: '022-482-3090',
      emailAddress: 'malmesburysheriff@telkomsa.net',
      province: 'Western Cape',
      postalCode: '7300',
    ),
    SheriffModel(
      sheriffName: 'Mr Hennie Jordaan',
      magisterialDistrict: 'Kuilsrivier HL',
      address: 'Office 5, The Boulevard, Soutrivier, 7570',
      postalAddress: 'P.O. Box 7570, Kuilsrivier, 7580',
      officeLine: '021-903-8134',
      cellNumber: '082-564-9043',
      emailAddress: 'sheriffkuilsrivier@gmail.com',
      province: 'Western Cape',
      postalCode: '7570',
    ),
    SheriffModel(
      sheriffName: 'Mr Pieter Andries Rossouw',
      magisterialDistrict: 'Albertinia HL',
      address: '124 Versveld Street, Riversdale, 6670',
      postalAddress: '124 Versveld Street, Riversdale, 6670',
      officeLine: '068-424-1794',
      cellNumber: '060-505-8745',
      province: 'Western Cape',
      postalCode: '6670',
    ),
    SheriffModel(
      sheriffName: 'Mr Hendrick Christoffel Ackerman',
      magisterialDistrict: 'Khayelitsha HL',
      address: '20 Sierra Way, Mandalay, 7785',
      postalAddress: '20 Sierra Way, Mandalay, 7785',
      officeLine: '021-388-5632',
      province: 'Western Cape',
      postalCode: '7785',
    ),
    SheriffModel(
      sheriffName: 'Mr Thabang Peter Mokwena',
      magisterialDistrict: 'De Aar HL',
      address: '21 Alida Street, De Aar, South Africa, 7000',
      postalAddress: 'P.O. Box 460, De Aar, 7000',
      officeLine: '053-631-0062',
      cellNumber: '079-509-4107',
      emailAddress: 'mokwenashariff@gmail.com',
      province: 'Northern Cape',
      postalCode: '7000',
    ),
    SheriffModel(
      sheriffName: 'Mr Victor Charles Rowland Daniel',
      magisterialDistrict: 'Sasolsburg HL',
      address: '12 Hobson Crescent, Sasolsburg, 1947',
      postalAddress: 'P.O. Box 297, Sasolsburg, 9570',
      officeLine: '016-976-0568',
      province: 'Free State',
      postalCode: '1947',
    ),
    SheriffModel(
      sheriffName: 'Mr Gerald Daniel Itumeleng Malao',
      magisterialDistrict: 'Tlokwe (Potchefstroom) HL',
      address: 'No. 8 Luke Street, Potchefstroom, 2531',
      postalAddress: 'No. 8 Luke Street, Potchefstroom, 2531',
      officeLine: '067-375-2812',
      emailAddress: 'admin@sheriffpotch.co.za',
      province: 'North West',
      postalCode: '2531',
    ),
    SheriffModel(
      sheriffName: 'Mr Thabiso Anthony Mtsweni',
      magisterialDistrict: 'Kwa-Lugedlane HL',
      address: '36 Fitzgerald Street, 3 Kwelanga Accommodation, Belfast, 1100',
      postalAddress: 'Private Bag X4026, Kwa-Lugedlane, 1341',
      officeLine: '013-170-5903',
      cellNumber: '082-586-5563',
      province: 'Mpumalanga',
      postalCode: '1341',
    ),
    SheriffModel(
      sheriffName: 'Mr Mbongeni George',
      magisterialDistrict: 'Port St Johns HL',
      address:
          '71 Cumberland Street, Umtata Central, Mthatha, South Africa, 5100',
      postalAddress: 'P.O. Box 797, Cala, 5455',
      officeLine: '047-110-9124',
      cellNumber: '076-107-2858',
      emailAddress: 'Mbongenigeorge99@gmail.com',
      province: 'Eastern Cape',
      postalCode: '5100',
    ),
    SheriffModel(
      sheriffName: 'Mrs Anna Magrieta Erasmus',
      magisterialDistrict: 'Randfontein HL',
      address:
          'Old ABSA Building, CNR Kruger & Human Streets, Krugersdorp, 1740',
      postalAddress: 'P.O. Box 364, Randfontein, 1760',
      officeLine: '010-534-9351',
      emailAddress: 'Nthabiseng@sheriffrandfontein.co.za',
      province: 'Gauteng',
      postalCode: '1739',
    ),
    SheriffModel(
      sheriffName: 'Mr Ivan Roy Swart',
      magisterialDistrict: 'Heidelberg HL',
      address: '40 Mare Street, Heidelberg, 1441',
      postalAddress: 'P.O. Box 1006, Delmas, 2210',
      officeLine: '064-807-3093',
      emailAddress: 'sherifheidlebalfour@gmail.com',
      province: 'Gauteng',
      postalCode: '1441',
    ),
    SheriffModel(
      sheriffName: 'Ms Mmankwe Ancilia Blantina Mahlangu',
      magisterialDistrict: 'Centurion West HL',
      address: '22 Voortrekker Street, Edenvale, 1600',
      postalAddress: 'P.O. Box 2487, Lyttleton, 0140',
      officeLine: '012-663-8344',
      cellNumber: '076-943-4663',
      province: 'Gauteng',
      postalCode: '1600',
    ),
    SheriffModel(
      sheriffName: 'Mr Antonie Christoffel Van Rooyen',
      magisterialDistrict: 'Port Elizabeth North L',
      address: '12 Theale Street, Port Elizabeth, 6001',
      postalAddress: 'P.O. Box 27123, Port Elizabeth, 6050',
      officeLine: '041-373-3112',
      cellNumber: '082-892-2300',
      emailAddress: 'antonie.sheriff@mweb.co.za',
      province: 'Eastern Cape',
      postalCode: '6001',
    ),
  ];
}
